### ISSUE TITLE
Urgent Forms v2.0.14 | Release date 24.09.2015 

### ISSUE THREAD

**Issue by bilal-ahmed-dev** [ThemeFuse/Unyson-Extensions-Approval#144]
Hello @moldcraft 

Is this form extension version available in Unyson 2.4.8 version

Thanks

**Comment by ghost** [comment]
Extension versions are not hardcoded in Unyson.
Unyson fetches [the latest release from Github repository](https://github.com/ThemeFuse/Unyson-Forms-Extension/releases).
