### ISSUE TITLE
Sliders v1.1.5 | Release date 19.01.2015

### ISSUE THREAD

**Issue by llemurya** [ThemeFuse/Unyson-Extensions-Approval#2]
## Chagelog
- Added filter `fw_ext_slider_activated` you can use it if you want to disable some core sliders
## Test

[Download](https://github.com/ThemeFuse/Unyson-Sliders-Extension/releases/tag/v1.1.5) 
and extract in `framework/extensions/media/extensions/slider/`

**Comment by ghost** [comment]
Released
