### ISSUE TITLE
Builder 1.1.6 | Release date: 18.02.2015

### ISSUE THREAD

**Issue by ghost** [ThemeFuse/Unyson-Extensions-Approval#20]
## Chagelog
- Made builder header fixed on scroll down

![ezgif-23181850](https://cloud.githubusercontent.com/assets/1475489/6213852/a7aad062-b5fc-11e4-9fa6-d850e987a0f0.gif)
## Test

[Download](https://github.com/ThemeFuse/Unyson-Builder-Extension/releases/tag/v1.1.6) and extract in `framework/extensions/builder/`

**Comment by ghost** [comment]
I moved the release date to 18.02.2015 to release it together with other 2 extensions

**Comment by AminulBD** [comment]
Hi,

This is not working for me. I've updated latest version of builder extension.

**Comment by ghost** [comment]
Hi,  what is exactly is not working?
