### ISSUE TITLE
Mega Menu v1.0.4 | Release date 20.02.2015

### ISSUE THREAD

**Issue by ghost** [ThemeFuse/Unyson-Extensions-Approval#23]
## Chagelog
- Added filters for [container element](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/v1.0.4/includes/class-fw-ext-mega-menu-walker.php#L156-L165) and [`<ul>` classes](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/v1.0.4/includes/class-fw-ext-mega-menu-walker.php#L181-L188)
- A cleaner way to [extend the walker](https://github.com/ThemeFuse/Unyson/issues/79#issuecomment-74970280)
- Code refactor
  - Fixed [function and class prefixes](http://manual.unyson.io/en/latest/convention/prefixes.html#extensions)
  - Moved some code from extension class to [`hooks.php`](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/v1.0.4/hooks.php), to be able to make `remove_filter()` in `{theme}/framework-customizations/extensions/megamenu/hooks.php`
## Test

[Download](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/releases/tag/v1.0.4) and extract in `framework/extensions/megamenu/`

**Comment by danyj** [comment]
Tested works ok 

Heads up to developers who extended the  FW_Theme_Menu_Walker already 

following methods have been changed from private to protected 

```
private function megamenu(...

private function row_has_icons(...

private function sub_menu_has_icons(...

// changed to

protected function megamenu(...

protected function row_has_icons(...

protected function sub_menu_has_icons(...
```

**Comment by ghost** [comment]
Thank you for testing.

---

Also thank you for pointing out the methods. To prevent errors or warnings for developers that already extended FW_Theme_Menu_Walker, I will revert those methods to private and create new methods with new names that does the same but are protected, and old private methods will call those new protected methods.

**Comment by danyj** [comment]
:100:

**Comment by ghost** [comment]
[done](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/commit/28d9ebbd069465223f5281e47fd2f3fd4e603723) _(you can redownload from the same link above)_

**Comment by danyj** [comment]
works
