### ISSUE TITLE
Sliders v1.1.6 | Release date 02.03.2015

### ISSUE THREAD

**Issue by ghost** [ThemeFuse/Unyson-Extensions-Approval#27]
## Chagelog
- Make in extension `array_merge($old_values, $new_values)` for slider post options, because that functionality will be removed from core in the next release https://github.com/ThemeFuse/Unyson/issues/266
## Test

[Download](https://github.com/ThemeFuse/Unyson-Sliders-Extension/releases/tag/v1.1.6) and extract in `framework/extensions/media/extensions/slider/`

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson-Sliders-Extension/releases/tag/v1.1.6
