### ISSUE TITLE
Population Methods v1.0.5 | Release date 19.01.2015

### ISSUE THREAD

**Issue by llemurya** [ThemeFuse/Unyson-Extensions-Approval#3]
## Changelog
- Resolve bug when `custom-settings` in `get_frontend_data` were undefined for categories, tags and posts
- Set `post_id` in `'extra' => array('post_id' => $post->ID)` in order to retrieve data by 'post_id'
- Resolve bug when slider is removed by filter `fw_ext_slider_activated` to work properly
## Test

[Download](https://github.com/ThemeFuse/Unyson-PopulationMethods-Extension/releases/tag/v1.0.5)
and extract in `framework/extensions/media/extensions/population-method/`

**Comment by ghost** [comment]
Released
