### ISSUE TITLE
Backup 2.0.24 | Release date 14.04.2017

### ISSUE THREAD

**Issue by GheorgheP** [ThemeFuse/Unyson-Extensions-Approval#347]
### Changelog

* Fixed https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/43
* Fixed https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/44

https://github.com/ThemeFuse/Unyson-Backups-Extension/compare/v2.0.23...v2.0.24

### Test

[Download](https://github.com/ThemeFuse/Unyson-Backups-Extension/releases/tag/v2.0.24) and extract in `unyson/framework/extensions/backups`.

**Comment by BassemN** [comment]
:+1:

**Comment by GheorgheP** [comment]
I'm sorry, I meant to release the extension on Thursday, but I missed up with date.
