### ISSUE TITLE
Forms 2.0.31 | Release date 30.05.2017

### ISSUE THREAD

**Issue by GheorgheP** [ThemeFuse/Unyson-Extensions-Approval#349]
### Changelog

* Fixed https://github.com/ThemeFuse/Unyson/issues/2600
* Fixed re-captcha from item type
* Fixed https://github.com/ThemeFuse/Unyson/issues/2466
* Fixed https://github.com/ThemeFuse/Unyson/issues/2299
* Fixed https://github.com/ThemeFuse/Unyson-Forms-Extension/issues/17
* Fixed https://github.com/ThemeFuse/Unyson/issues/2230

https://github.com/ThemeFuse/Unyson-Forms-Extension/compare/v2.0.29...v2.0.31

### Test

[Download](https://github.com/ThemeFuse/Unyson-Forms-Extension/releases/tag/v2.0.31) and extract in `unyson/framework/extensions/forms`.

**Comment by danyj** [comment]
@GheorgheP  How about these 

https://github.com/ThemeFuse/Unyson/issues/2509
https://github.com/ThemeFuse/Unyson/issues/2507

**Comment by GheorgheP** [comment]
They are open, so we will solve them, but in the next version(s).

**Comment by danyj** [comment]
I am sorry but how is this productive? 2 issues almost 2 months old , unsolved , bugs confirmed , I advised of it 6 days ago and now wait for next version which will be when?  Another 5 months?

**Comment by danyj** [comment]
Why do we have Unyson-Extensions-Approval if this is one sided decision?

**Comment by xperter** [comment]
After moldcarft gone Unyson also gone slowly. There support going worst day by day.
Unyson Was my favorite framework. But now I do not share anyone to use unyson. We will not build our themes with unyson in future.

**Comment by xperter** [comment]
@DimiBaitanciuc  @danyj After moldcarft gone Unyson also gone slowly. There support going worst day by day.
Unyson Was my favorite framework. But now I do not share anyone to use unyson. We will not build our new themes with unyson in future.

**Comment by DKudleichuk** [comment]
+1 for worst and slow support

**Comment by danyj** [comment]
@WPJobs @xperter , take it easy guys ,  we all seen some downtime but if we are all in it together  lets solve this in a way that works for all of us. Trowing stones does not help us now at all.  I know and you know that we all have put hundreds of hours in to testing and working with Unyson. We cant just drop it now. 

I am sure that team knows what needs to be done next but from my perspective seems like priorities got mixed up. It should be first come first served and not lets see when we get to it.

**Comment by danyj** [comment]
also thnx for support but if we would have supported the bugs the way we support "bad" feelings , I am sure they would have been solved.  As far as I can see many bugs we report we get to hang in them alone. No one does a thumbs up + or a simple comment saying , yes I also have this issue.

**Comment by GheorgheP** [comment]
@danyj Reading the [How it works](https://github.com/ThemeFuse/Unyson-Extensions-Approval#how-it-works) section explain fine for what is made this repository. As you can see, after posting a new version we wait for confirmation from community that this version is sable and doesn't break any functionality. It is not made to decide what issues to be solved within, because this can continue to infinity. 
What about issues that were reported 2 weeks ago and are already included in new version and other that have 5 months are not. There are many reasons:

 - Usually when I get an issue and it is not sot complicated, I solve it just in time.
 - Some issues are critical and I have to solve them.
 - Other issues are reported I leave it in order to solve later, and I can even forget about it, because I'm focused on other things.
 - Some issues have really low priority, e.g. [#2507](https://github.com/ThemeFuse/Unyson/issues/2507) [#2509](https://github.com/ThemeFuse/Unyson/issues/2509). They are important too, but now breaking ones, like the fact that backup is not working or page builder is breaking the content, that's why we give them low priority.

*(I used the `I` instead of `We`, because I'm speaking about me only)*

@xperter @WPJobs I would really want to be able to help you fast and in time, but we are 2 developers only at this project, me and @andreiglingeanu, also big thanks to @danyj that is covering us always by reporting and helping users on many issues. Please thumb up on issues that affects you mostly, so we could know where to focus.

@xperter What do you mean by `Unyson also gone slowly`? The framework is working properly, @andreiglingeanu  introduced new reactive options, also we introduced the CLI module, working on cache module to make it faster. So for me is important to understand what is not right with Unyson now.
