### ISSUE TITLE
Unyson 2.7.5 | Release date 17.08.2017

### ISSUE THREAD

**Issue by GheorgheP** [ThemeFuse/Unyson-Extensions-Approval#358]
### Changelog

* Fixed [#2460](https://github.com/ThemeFuse/Unyson/issues/2460)
* Fixed [#1775](https://github.com/ThemeFuse/Unyson/issues/1775#issuecomment-293581057)
* Fixed [#2516](https://github.com/ThemeFuse/Unyson/issues/2516)
* Fixed [#2536](https://github.com/ThemeFuse/Unyson/pull/2536)
* Fixed [#1419](https://github.com/ThemeFuse/Unyson/issues/1419)
* Fixed [#2563](https://github.com/ThemeFuse/Unyson/issues/2563)
* Fixed [#2587](https://github.com/ThemeFuse/Unyson/issues/2587)
* Fixed [#2591](https://github.com/ThemeFuse/Unyson/issues/2591)
* Fixed [#2604](https://github.com/ThemeFuse/Unyson/issues/2604)
* New feature. Introducing Reactive Option Types

https://github.com/ThemeFuse/Unyson/compare/v2.6.16...v2.7.5

### Test

[Download](https://github.com/ThemeFuse/Unyson/releases/tag/v2.7.5) and extract in `wp-content/plugins/unyson`

**Comment by andronic90** [comment]
Problem with RGBA: https://static.md/93783f8185e0d8db3f3156a837aad7db.png, the input need to be colored

**Comment by BassemN** [comment]
@andronic90 Out of the topic question, I need to display the theme settings like your [screenshot](https://static.md/93783f8185e0d8db3f3156a837aad7db.png) but it is always displayed in tabs, so please how can I display like yours?

**Comment by andronic90** [comment]
@BassemN You can use this link: http://manual.unyson.io/en/latest/convention/directory-structure.html

file: "framework-customizations/theme/config.php"
```
$cfg = array(
    // Theme Settings form ajax submit
    'settings_form_ajax_submit' => true,
    // Theme Settings side tabs
    'settings_form_side_tabs' => true,
);
```

**Comment by BassemN** [comment]
@andronic90 Thank you very much :) I'll try this
