### ISSUE TITLE
Translation v1.0.0 | Release date 26.03.2015

### ISSUE THREAD

**Issue by ghost** [ThemeFuse/Unyson-Extensions-Approval#36]
Initial release
## Test

[Download](https://github.com/ThemeFuse/Unyson-Translation-Extension/releases/tag/v1.0.0) and extract in `framework/extensions/translation/`

**Comment by GheorgheP** [comment]
The version v1.0.0 will be suspended for a while...

**Comment by ghost** [comment]
The release date was set to 26.03.2015

**Comment by ghost** [comment]
Will be available in Unyson 2.2.6
