### ISSUE TITLE
UNYSON 2.7.7

### ISSUE THREAD

**Issue by GlobalAffects** [ThemeFuse/Unyson-Extensions-Approval#360]
Hi there - I just loaded new theme that depends upon Pagebuilder - using Unyson 2.7.7 and when PAGE BUILDER is active - and you attempt to create or edit a page, post or custom post - the page loads blank and says forbidden

troubleshooting - 
turned off ALL PLUGINS - and error is the same - 
turn off PAGEBUILDER and can open and edit any kind of post or page

any ideas on how to troubleshoot?

Thanks
Annie

AlkaWeb theme developer - STARRY theme 1.3.3
Wordpress = 4.8.2 - Unyson 2.7.7

### Changelog

* ... 

https://github.com/ThemeFuse/Unyson-NAME-Extension/compare/vX.X.X...vX.X.X

### Test

[Download](https://github.com/ThemeFuse/Unyson-NAME-Extension/releases/tag/vX.X.X) and extract in `unyson/framework/extensions/...`

**Comment by ViorelEremia** [comment]
This is a theme issue, can be for many reasons without having the code we can not predict anything

**Comment by GlobalAffects** [comment]
OK - thanks, VE!
