### ISSUE TITLE
Unyson-Mailer-Extension 1.2.12 | Release date 26.01.2018

### ISSUE THREAD

**Issue by ViorelEremia** [ThemeFuse/Unyson-Extensions-Approval#367]
### Changelog

* https://github.com/ThemeFuse/Unyson/issues/2993

https://github.com/ThemeFuse/Unyson-Mailer-Extension/compare/v1.2.11...v1.2.12

### Test

[Download](https://github.com/ThemeFuse/Unyson-Mailer-Extension/releases/tag/v1.2.12) and extract in `unyson/framework/extensions/mailer`

**Comment by danyj** [comment]
seems ok now

**Comment by danyj** [comment]
but before release you might want to look at this 
https://github.com/ThemeFuse/Unyson/issues/3141
