### ISSUE TITLE
Shortcodes v1.2.7 | Release date 19.01.2015

### ISSUE THREAD

**Issue by rockalife** [ThemeFuse/Unyson-Extensions-Approval#4]
## Changelog
- closed [#7](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/issues/7)
- shortcodes static files now are enqueued in `<head>`
- other minor fixes
## Test

[Download](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/releases/tag/v1.2.7) and extract in `framework/extensions/shortcodes/`

**Comment by ghost** [comment]
Released
