### ISSUE TITLE
Builder v1.1.8 | Release date 01.04.2015

### ISSUE THREAD

**Issue by GheorgheP** [ThemeFuse/Unyson-Extensions-Approval#49]
## Chagelog
- Fixed a bug with builder items ordering
## Test

[Download](https://github.com/ThemeFuse/Unyson-Builder-Extension/archive/v1.1.8.zip) and extract in `framework/extensions/builder/`

**Comment by erralb** [comment]
Hi, is this fixing https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/26#issuecomment-86440174 ?

**Comment by GheorgheP** [comment]
Yes
